<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-HCFSD6K" failures="5" tests="7" name="Invoice Data Check" time="1.564" errors="0" timestamp="2025-07-05T14:19:21 IST">
  <testcase classname="validator.InvoiceValidationTest" name="validateInvoice" time="0.025"/>
  <testcase classname="validator.InvoiceValidationTest" name="validateInvoice" time="0.018">
    <failure type="java.lang.AssertionError" message="❌ Invoice failed: Invoice_Row_2 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ❌ Invoice failed: Invoice_Row_2 expected [true] but found [false]
at validator.InvoiceValidationTest.validateInvoice(InvoiceValidationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateInvoice -->
  <testcase classname="validator.InvoiceValidationTest" name="validateInvoice" time="0.003">
    <failure type="java.lang.AssertionError" message="❌ Invoice failed: Invoice_Row_3 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ❌ Invoice failed: Invoice_Row_3 expected [true] but found [false]
at validator.InvoiceValidationTest.validateInvoice(InvoiceValidationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateInvoice -->
  <testcase classname="validator.InvoiceValidationTest" name="validateInvoice" time="0.003">
    <failure type="java.lang.AssertionError" message="❌ Invoice failed: Invoice_Row_4 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ❌ Invoice failed: Invoice_Row_4 expected [true] but found [false]
at validator.InvoiceValidationTest.validateInvoice(InvoiceValidationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateInvoice -->
  <testcase classname="validator.InvoiceValidationTest" name="validateInvoice" time="0.003"/>
  <testcase classname="validator.InvoiceValidationTest" name="validateInvoice" time="0.004">
    <failure type="java.lang.AssertionError" message="❌ Invoice failed: Invoice_Row_6 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ❌ Invoice failed: Invoice_Row_6 expected [true] but found [false]
at validator.InvoiceValidationTest.validateInvoice(InvoiceValidationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateInvoice -->
  <testcase classname="validator.InvoiceValidationTest" name="validateInvoice" time="0.008">
    <failure type="java.lang.AssertionError" message="❌ Invoice failed: Invoice_Row_7 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: ❌ Invoice failed: Invoice_Row_7 expected [true] but found [false]
at validator.InvoiceValidationTest.validateInvoice(InvoiceValidationTest.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- validateInvoice -->
</testsuite> <!-- Invoice Data Check -->
